import type { Metadata } from "next";
import '../styles/global.scss';
import {AuthProvider} from "@/context/AuthContext";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
            <Header/>
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}
